GET http://localhost:4000/health
###
GET http://localhost:4000/api/raffledraw
###
POST http://localhost:4000/api/raffledraw
Content-Type: application/json

{
  "username": "Vumi Madhu",
  "price": 1
}

###
GET http://localhost:4000/api/raffledraw

###
GET http://localhost:4000/api/raffledraw/ticket/ePRZeaTNNnKoLj1np2_dA
